services:
  - type: web
    name: sharks
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn sharks.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sharks.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
